# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [38]:
import numpy as np
data = np.arange(10)
print(data)
data = data.reshape(2,5)
data

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [25]:
a=np.arange(10).reshape(2,5)
b=np.ones((10,),dtype=int).reshape(2,5)
##print(a)
##print(b)
print(np.vstack((a,b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [23]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [34]:
arr = np.arange(10).reshape(5,2)
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [47]:
data = np.arange(36).reshape(3,4,3)
print(data)
print(data.ravel())


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [51]:
data = np.arange(15)
print(data)
data.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [56]:
arr = np.random.rand(5,5)*10
np.sqrt(arr)

array([[3.08019052, 2.09539677, 0.90353472, 2.96029069, 0.55677691],
       [2.92105968, 2.89203687, 2.23168177, 1.50590193, 2.47487904],
       [2.74813726, 0.75275983, 1.13951926, 2.41379287, 2.79142006],
       [1.62074031, 2.94400506, 3.00548775, 2.5153848 , 1.91222841],
       [2.02222398, 2.97424638, 2.79596224, 2.38937419, 1.95032586]])

## Question:8

### Create 5x6 an array and find the mean?

In [67]:
data = np.random.randint(0,100,size=(5,6))
np.mean(data)

47.6

## Question:9

### Find the standard deviation of the previous array in Q8?

In [69]:
data = np.random.randint(0,100,size=(5,6))
np.std(data)

28.04868782829045

## Question:10

### Find the median of the previous array in Q8?

In [70]:
data = np.random.randint(0,100,size=(5,6))
np.median(data)

47.5

## Question:11

### Find the transpose of the previous array in Q8?

In [71]:
data = np.random.randint(0,100,size=(5,6))
np.transpose(data)

array([[83, 96, 82, 67, 24],
       [13, 25, 89, 54, 44],
       [88, 76, 85, 97, 78],
       [ 0, 14, 18, 53, 58],
       [38, 55, 86, 53,  2],
       [95, 64, 93, 29, 62]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [75]:
data = np.random.randint(0,50,size=(4,4))
data.trace()

98

## Question:13

### Find the determinant of the previous array in Q12?

In [76]:
data = np.random.randint(0,50,size=(4,4))
np.linalg.det(data)

858802.0000000002

## Question:14

### Find the 5th and 95th percentile of an array?

In [ ]:
data = np.arange(100)
print("5th percentile of arr : ",np.percentile(data, 5))
print("95th percentile of arr : ",np.percentile(data, 95))

## Question:15

### How to find if a given array has any null values?

In [83]:
data = np.identity(5)
data[1,0] = None
data[2,1] = None
np.isnan(data)

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])