# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
zeros = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [57]:
vect = np.arange(10,49)
vect

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [54]:
vect.shape

(39,)

5. Print the type of the previous array in question 3

In [9]:
vect.dtype

int32


6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.show_config())

1.19.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [58]:
vect.ndim

1

8. Create a boolean array with all the True values

In [62]:
bool_array = np.array([True, True, True, True])
bool_array

array([ True,  True,  True,  True])

9. Create a two dimensional array

In [66]:
two_dim_arr = np.random.rand(2,2)

10. Create a three dimensional array

In [68]:
three_dim_arr = np.random.rand(3,3,3)

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [20]:
initalizer_array = np.array([111, 222, 333, 444, 555, 666]) 
reverce_arr = initalizer_array[::-1]
print(reverce_arr)

[666 555 444 333 222 111]


12. Create a null vector of size 10 but the fifth value which is 1 

In [21]:
nul_vect = np.zeros(10)
print(nul_vect)
print("Update fifth value to 11")
nul_vect[5] = 1
print(nul_vect)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [70]:
id_matx = np.identity(3, dtype=int)

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [25]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
result = arr1* arr2
result    

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [74]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 6.],[7., 2., 12.]])
compare = arr1 == arr2
compare

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [82]:
num_arr = np.arange(10)
print(num_arr)
odd_num_arr = num_arr[num_arr%2 == 1]
print(odd_num_arr)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [83]:
new_array = np.where(num_arr%2==1,-1,num_arr)
print(new_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [84]:
arr = np.arange(10)
arr[4]=arr[5]=arr[6]=arr[7]=12
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [87]:
x = np.ones((5,5), dtype=int)
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 on the border and 0 inside in the array
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [88]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[arr2d==5] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [100]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [204]:
two_dim_arr = np.random.randint(low=0, high=9,size =(3,4))
print(two_dim_arr)
two_dim_arr[0, 0:4]

[[0 2 4 3]
 [5 1 8 4]
 [3 0 6 1]]


array([0, 2, 4, 3])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [196]:
two_dim_arr = np.random.randint(low=0, high=9, size =(3,4))
print(two_dim_arr)
two_dim_arr[1 , 1]

[[7 8 6 1]
 [8 4 7 2]
 [8 8 7 5]]


4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [207]:
two_dim_arr = np.random.randint(low=0, high=9, size =(3,4))
print(two_dim_arr)
two_dim_arr[:2,2:]

[[1 6 7 3]
 [6 6 7 6]
 [7 1 7 7]]


array([[7, 3],
       [7, 6]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [218]:
data = np.random.randn(10,10)
val_max = data.max()
val_min = data.min()
print('Max val:', val_max, ' Min val: ', val_min)

Max val: 3.12108540377165  Min val:  -2.9748588830077383


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [226]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [230]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b)
print(c)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [233]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[~(names == "Will")]

array([[-1.01415867, -1.81351589,  0.39626176,  0.93582324],
       [-0.09309932,  0.6236419 ,  0.33634409, -0.23835352],
       [ 0.88965389, -1.2111858 ,  0.04647254, -0.64549575],
       [ 2.39443261,  0.14824572, -1.30723574,  0.61010956],
       [ 0.25638847, -1.32851907, -1.52514216, -1.40136443]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [240]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
msk = (names == "Will") | (names == "Joe")
data[~msk]

array([[-0.97915281,  1.42422128,  0.66367332, -0.05312507],
       [-0.56917924,  0.0371518 ,  1.12189647,  1.2342336 ]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
arr= np.random.randint(low= 1,high = 15, size =(5,3) , dtype=int)
arr

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [245]:
arr= np.random.randint(low= 1,high = 16, size =(2,2,4) , dtype=int)
arr

array([[[ 3,  7, 15,  6],
        [ 1, 15,  8, 12]],

       [[ 6,  2,  6, 13],
        [ 8,  4,  4, 14]]])

33. Swap axes of the array you created in Question 32

In [246]:
arr.swapaxes(1,2)

array([[[ 3,  1],
        [ 7, 15],
        [15,  8],
        [ 6, 12]],

       [[ 6,  8],
        [ 2,  4],
        [ 6,  4],
        [13, 14]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [252]:
arr = np.random.random(10)
n_arr = np.where(np.sqrt(arr)<0.5,0,arr)
print(n_arr)

[0.97193294 0.         0.58754244 0.36031594 0.         0.
 0.72433489 0.95712245 0.         0.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [261]:
arr1 = np.random.random(12)
arr2 = np.random.random(12)

n_arr = np.maximum(arr1,arr2)
n_arr


array([0.81287848, 0.49284596, 0.9842942 , 0.91645944, 0.85618362,
       0.67184476, 0.60376969, 0.24081943, 0.96289899, 0.62485299,
       0.94140964, 0.77048013])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [265]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = np.unique(names)
names.sort()
names

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [266]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [267]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
sampleArray[1] = newColumn
sampleArray

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [273]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
x.dot(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [282]:
twenty_random = np.random.randn(5,4)
csum = twenty_random.cumsum()
csum

array([-0.25322878,  0.41704941,  1.47792075,  1.6786821 ,  1.94168838,
        2.54350404,  2.87849082,  2.09585934,  1.90654475,  1.28012506,
        2.61994974,  2.52454341,  2.31641529,  1.2438814 , -1.10869662,
        1.00415961,  0.97743464,  1.04450986,  0.790581  ,  0.26516383])